spring:
  application:
    name: config-server
  profiles:
    active:
      - native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/csdavidg/config.git
          searchPaths: licensingservice

server:
  port: 8071